name: Print on external push

# Controls when the action will run. Triggers the workflow on repository_dispatch and filters by type of event (i.e. `event_type`)
on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      action:
        description: Excecute Action
        required: true
      service-name:
        description: Service Name
      environment:
        type: string
        description: Environment 
  repository_dispatch:
    types: [sample_push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other custom actions to build,
          echo test, and deploy your project.

      - name: Event Information
        run: | 
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
          echo "Event '${{ github.event.inputs.action }}' - '${{ github.event.inputs.service-name }}' - '${{ github.event.inputs.environment }}'"
 